name: Publish Test App

on:
  push:
    branches: [ update-test-app ]
  pull_request:
    branches: [ update-test-app ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk'

      - name: Upload Bintray Test App
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew :keepup-tests:bintray-tests:bintrayUp

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk'

      - name: Upload Bintray Test App
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew :keepup-tests:bintray-tests:bintrayUp

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk'

      - name: Upload Bintray Test App
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew :keepup-tests:bintray-tests:bintrayUp
